// Generated by gencpp from file heartbeat_ros/Contact.msg
// DO NOT EDIT!


#ifndef HEARTBEAT_ROS_MESSAGE_CONTACT_H
#define HEARTBEAT_ROS_MESSAGE_CONTACT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heartbeat_ros
{
template <class ContainerAllocator>
struct Contact_
{
  typedef Contact_<ContainerAllocator> Type;

  Contact_()
    : pressure()  {
    }
  Contact_(const ContainerAllocator& _alloc)
    : pressure(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _pressure_type;
  _pressure_type pressure;





  typedef boost::shared_ptr< ::heartbeat_ros::Contact_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heartbeat_ros::Contact_<ContainerAllocator> const> ConstPtr;

}; // struct Contact_

typedef ::heartbeat_ros::Contact_<std::allocator<void> > Contact;

typedef boost::shared_ptr< ::heartbeat_ros::Contact > ContactPtr;
typedef boost::shared_ptr< ::heartbeat_ros::Contact const> ContactConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heartbeat_ros::Contact_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heartbeat_ros::Contact_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::heartbeat_ros::Contact_<ContainerAllocator1> & lhs, const ::heartbeat_ros::Contact_<ContainerAllocator2> & rhs)
{
  return lhs.pressure == rhs.pressure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::heartbeat_ros::Contact_<ContainerAllocator1> & lhs, const ::heartbeat_ros::Contact_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace heartbeat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::heartbeat_ros::Contact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heartbeat_ros::Contact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heartbeat_ros::Contact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heartbeat_ros::Contact_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heartbeat_ros::Contact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heartbeat_ros::Contact_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heartbeat_ros::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "620ca9b8e487092667c7d7be8066ab46";
  }

  static const char* value(const ::heartbeat_ros::Contact_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x620ca9b8e4870926ULL;
  static const uint64_t static_value2 = 0x67c7d7be8066ab46ULL;
};

template<class ContainerAllocator>
struct DataType< ::heartbeat_ros::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heartbeat_ros/Contact";
  }

  static const char* value(const ::heartbeat_ros::Contact_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heartbeat_ros::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message format for raw sensor data\n"
"bool[] pressure\n"
;
  }

  static const char* value(const ::heartbeat_ros::Contact_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heartbeat_ros::Contact_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Contact_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heartbeat_ros::Contact_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heartbeat_ros::Contact_<ContainerAllocator>& v)
  {
    s << indent << "pressure[]" << std::endl;
    for (size_t i = 0; i < v.pressure.size(); ++i)
    {
      s << indent << "  pressure[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.pressure[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEARTBEAT_ROS_MESSAGE_CONTACT_H
